version: '3.8'

services:
    repairlog:
        build:
            context: .
            dockerfile: Dockerfile
        image: repairlog
        container_name: repairlog
        restart: unless-stopped
        env_file:
            - ./.env
        environment:
            - DB_HOST=localhost
            - DB_USER=superuser
            - DB_PASSWORD=1234
            - DB_NAME=mockdb
            - DB_PORT=3306
        ports:
            - 8000:8000
volumes:
    db:
